apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    opendatahub.io/template-enabled: "true"
    tags: triton-23.05-20230630,servingruntime
    argocd.argoproj.io/sync-wave: "2"
    description: Nvidia Triton Inference Server Runtime Definition
  labels:
    opendatahub.io/configurable: "true"
    opendatahub.io/dashboard: "true"
  name: triton-inference-server
objects:
- apiVersion: serving.kserve.io/v1alpha1
  kind: ServingRuntime
  metadata:
    annotations:
      maxLoadingConcurrency: "2"
      openshift.io/display-name: Triton runtime 23.05 - added on 20230630
    labels:
      name: triton-23.05-20230630
    name: triton-23.05-20230630
  spec:
    builtInAdapter:
      memBufferBytes: 134217728
      modelLoadingTimeoutMillis: 90000
      runtimeManagementPort: 8001
      serverType: triton
    containers:
    - args:
      - -c
      - 'mkdir -p /models/_triton_models; chmod 777 /models/_triton_models; exec tritonserver
        "--model-repository=/models/_triton_models" "--model-control-mode=explicit"
        "--strict-model-config=false" "--strict-readiness=false" "--allow-http=true"
        "--allow-sagemaker=false" '
      command:
      - /bin/sh
      image: nvcr.io/nvidia/tritonserver:23.05-py3
      livenessProbe:
        exec:
          command:
          - curl
          - --fail
          - --silent
          - --show-error
          - --max-time
          - "9"
          - http://localhost:8000/v2/health/live
        initialDelaySeconds: 5
        periodSeconds: 30
        timeoutSeconds: 10
      name: triton
      resources:
        limits:
          cpu: "5"
          memory: 1Gi
        requests:
          cpu: 500m
          memory: 1Gi
    grpcDataEndpoint: port:8001
    grpcEndpoint: port:8085
    multiModel: true
    protocolVersions:
    - grpc-v2
    supportedModelFormats:
    - autoSelect: true
      name: keras
      version: "2"
    - autoSelect: true
      name: onnx
      version: "1"
    - autoSelect: true
      name: pytorch
      version: "1"
    - autoSelect: true
      name: tensorflow
      version: "1"
    - autoSelect: true
      name: tensorflow
      version: "2"
    - autoSelect: true
      name: tensorrt
      version: "7"
