---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: serving-demo-gitops-setup
  annotations:
    argocd.argoproj.io/sync-wave: "1"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: serving-demo-gitops-setup-cluster-reader
  annotations:
    argocd.argoproj.io/sync-wave: "1"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: serving-demo-gitops-setup
  namespace: serving-demo-gitops
